//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayTrackRest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class play0dbEntities : DbContext
    {
        public play0dbEntities()
            : base("name=play0dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMPONENTE> COMPONENTES { get; set; }
        public virtual DbSet<DISPOSITIVO> DISPOSITIVOS { get; set; }
        public virtual DbSet<REGISROS_USOS> REGISROS_USOS { get; set; }
    }
}
